### ISSUE TITLE
SD card initialization fails on FPGA

### ISSUE THREAD

**Issue by jbush001** [jbush001/NyuziProcessor#140]
Times out initializing card in SPI mode. It seems to never read anything but 0xff from the data out (DO) pin after sending CMD0.

1. Connected pins to GPIO block. I verified I could read the input pins (printed to the serial log) by shorting the solder pads to ground, and drive output pins by controlling with software and measuring with a multimeter.
2. I tried putting the chip into 4 bit mode. I could see correct data on DAT1-3, but DAT0 was stuck at VCC. I wrote various patterns on the SD card on my laptop, then re-read on the board to confirm.

**Comment by jbush001** [comment]
1. Connected pins to GPIO block. I verified I could read the input pins (printed to the serial log) by shorting the solder pads to ground, and drive output pins by controlling with software and measuring with a multimeter.
2. I tried putting the chip into 4 bit mode. I could see correct data on DAT1-3, but DAT0 was stuck at VCC. I wrote various patterns on the SD card on my laptop, then re-read on the board to confirm.

**Comment by jbush001** [comment]
Next steps:
- I'd like to obtain a USB logic analyzer/oscilloscope and probe what the signals are actually doing. Check both the timing of logic signals, but also analog characteristics like voltage to ensure they are in spec.
- One theory I have is that there is a mechanical problem with the connector, which seems like wishful thinking, but I could verify that by attaching an external SD card connector to one of the other headers.

**Comment by jbush001** [comment]
Simulation waveforms. Here is the initial clock sequence:

<img width="630" alt="init_clocks" src="https://user-images.githubusercontent.com/1145212/36651189-5bd97504-1a5c-11e8-8f37-d208bd6d63c0.png">

Here is CMD0:

<img width="638" alt="init_cmd0" src="https://user-images.githubusercontent.com/1145212/36651198-6b132524-1a5c-11e8-9d4b-a71ac99cdf1d.png">

```
01000000 00000000 00000000 00000000 00000000 10010101
40       00       00       00       00       95
CMD0 
``

**Comment by jbush001** [comment]
Verified 250 system clocks per spi clock: 200kHz SPI clock at 50Mhz system clock.

**Comment by jbush001** [comment]
While waiting for response:

<img width="250" alt="screen shot 2018-02-25 at 7 11 11 pm" src="https://user-images.githubusercontent.com/1145212/36651829-b0fb7372-1a5f-11e8-99a3-922b94a0ad76.png">

(Should CS be high here?)

**Comment by jbush001** [comment]
Tried with 3 cards, all failed in the same way (no response at all)
- 8 GB Samsung microSD (in adapter)
- 4 GB Monster SDHC
- 8 MB Canon

**Comment by jbush001** [comment]
I hooked up a logic analyzer and the first command worked correctly.

<img width="1224" alt="la_trace" src="https://user-images.githubusercontent.com/1145212/36929238-cfd374e8-1e42-11e8-8b5a-30886beae935.png">

Unplugged the logic analyzer and it started failing again... Seems like this might be a connector issue.

**Comment by jbush001** [comment]
I also had to turn the board upside down to attach the probes. In the normal position, gravity pulls the card down away from the pins. Upside down, it pushes them against them. I might try sticking a piece of paper in with the card to apply more pressure.

**Comment by jbush001** [comment]
I tried sticking paper in, turning the board around with no success. However, it works consistently if the probes are attached...

<img width="927" alt="screen shot 2018-03-03 at 11 38 01 am" src="https://user-images.githubusercontent.com/1145212/36938515-61041bfe-1ed7-11e8-82d2-317e61ea6d35.png">

**Comment by travisg** [comment]
Hmm, what board is that BTW?

**Comment by jbush001** [comment]
DE2-115

**Comment by travisg** [comment]
Ah didn't know if you were still using that. I actually bought one of those for myself when this project got started up years ago. I should brush it off.
