### ISSUE TITLE
I saw a similar crash in the user_copy_fault test.

### ISSUE THREAD

**Issue by John14lee** [jbush001/NyuziProcessor#191]
I saw a similar crash in the user_copy_fault test.

_Originally posted by @jbush001 in https://github.com/jbush001/NyuziProcessor/issues/171#issuecomment-447662050_

**Comment by jbush001** [comment]
Did you file this accidentally, or is this is a dup of #171?

**Comment by jbush001** [comment]
Closing for now as this seems to have been filed in error.
