### ISSUE TITLE
hi  how can i get linux  driver

### ISSUE THREAD

**Issue by weisuolong** [jbush001/NyuziProcessor#197]
i can not  find  linux driver  run opengl  to use this 
where can  i  get   it  
thank you~~

**Comment by jbush001** [comment]
This doesn't currently have an OpenGL driver and isn't a full featured graphics core.

**Comment by weisuolong** [comment]
How can I find a complete reference to the graphics core? Including opengl driver, thank you, any recommendations~

**Comment by jbush001** [comment]
Documentation is in the wiki, here: https://github.com/jbush001/NyuziProcessor/wiki
